config/routes.rb
Rails.application.routes.draw do
  default_url_options host: 'localhost:3000'

  devise_for :users
  root to: 'home#index'

  get 'my_send_proposals', to: 'profiles#my_send_proposals'

  resources :profiles, only:[:new, :create, :show, :edit, :update] do
    resources :ads, only: [:index]
    resources :reviews, only: [:new, :create]
  end

  get 'filter/ads', to: 'ads#filter'
  get 'my_proposals', to: 'proposals#my_proposals'

  resources :ads, only: [:new, :create, :show, :edit, :update] do
    post 'cancel', to: 'ads#cancel'
    post 'finish', to: 'ads#finish'
    resources :proposals, only:[:new, :create]
  end

  resources :proposals, only:[:show] do
    post 'approve', on: :member
    post 'reject', on: :member
  end

end

app/models/ad.rb
class Ad < ApplicationRecord
    has_many :proposals
    belongs_to :user

    enum status: [ :active, :finish, :cancelled ]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  validates :name, :birth_date, :city, :state, :skills, presence: true
  has_many :profile_reviews
  has_attached_file :photo, styles: { medium: '230x230>', thumb: '100x100>' },
                                     default_url: '/images/:style/missing.png'
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  def has_review_from_user? user
    self.profile_reviews.where(user: user).any?
  end
end

app/models/profile_review.rb
class ProfileReview < ApplicationRecord
  belongs_to :profile
  belongs_to :user
end

app/models/proposal.rb
class Proposal < ApplicationRecord

  belongs_to :user
  belongs_to :ad

    validates :description, :requested_knowledge, :email, :day_period,
              :meeting_type, presence:
              {message: 'Houve um erro ao tentar enviar a proposta' }

    enum status: [:pending, :approved, :rejected]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_one :profile
  has_many :proposals
  delegate :name, to: :profile
  has_many :ads
  has_many :profile_reviews

  def my_proposals
    active_ads = ads.where(status: :active)
    Proposal.where(ad: active_ads)
  end
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_action :authenticate_user!, only: %i[create new my_ads]

  def index
    @ads = current_user.ads
  end

  def show
    @ad = Ad.find(params[:id])
    @current_user_proposal = @ad.proposals.find_by(user: current_user)
  end

  def new
    if current_user.profile
      if current_user.ads.where(status: :active).any?
         flash[:notice] = 'Voce ja tem um anuncio ativo'
         redirect_to root_path
      else
        @ad = Ad.new
      end
    else
      redirect_to new_profile_path
    end
  end

  def create
    @ad = Ad.create(ad_params)
    @ad.user = current_user
    @ad.save
    redirect_to @ad
  end

  def edit
    @ad = Ad.find(params[:id])
  end

  def update
    @ad = Ad.find(params[:id])
    @ad.update(ad_params)
    redirect_to @ad
  end

  def filter
    @busca = params[:filter]
    @ads = Ad.where('requested_knowledge like  ? or offered_knowledge like  ? ',
                    "%#{@busca}%", "%#{@busca}%")
  end

  def finish
    @ad = Ad.find(params[:ad_id])
    @ad.finish!
    redirect_to @ad
  end


  def cancel
    @ad = Ad.find(params[:ad_id])
    @ad.cancelled!
    flash[:notice] = 'Anuncio cancelado com sucesso.'
    redirect_to @ad
  end

  private

  def ad_params
    params.require(:ad).permit(:title, :requested_knowledge, :offered_knowledge,
                               :meeting_type, :day_period, :location,
                               :avaliability)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @ads = Ad.all.where(status: :active)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(params_profile)
    @profile.user = current_user

    if @profile.save
      redirect_to root_path
      flash[:success] = 'Seu perfil está concluido, aproveite.'
    else
      flash[:error] = 'É necessario preencher todos os campos.'
      render :new
    end
  end

  def show
    @profile = Profile.find(params[:id])
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])
    @profile.update(params_profile)
    redirect_to @profile
  end

  def my_send_proposals
    @profile_proposals = current_user.proposals
  end

  private

  def params_profile
    params.require(:profile).permit(:name, :birth_date, :city,
                                    :state, :skills, :photo)
  end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_action :authenticate_user!, only: %i[new]
  before_action :find_ad, only: %i[create new show]

  def new
    @proposal = @ad.proposals.new
  end

  def create
    @proposal = @ad.proposals.new(proposal_params)
    @proposal.user = current_user
    @proposal.status = :pending
    if @proposal.save
      ProposalMailer.notify_new_proposal(@ad).deliver_now
      redirect_to @ad
    else
      flash[:error] = 'Houve um erro'
      render :new
    end
  end

  def my_proposals
    @proposals_approved = current_user.my_proposals.approved
    @proposals_rejected = current_user.my_proposals.rejected
    @proposals_pending = current_user.my_proposals.pending
  end

  def approve
    @proposal = Proposal.find(params[:id])
    @proposal.approved!

    flash[:notice] = 'Proposta aceita com sucesso.'
    ProposalMailer.notify_proposal_accepted(@proposal).deliver_now
    redirect_to my_proposals_path
  end

  def reject
    @proposal = Proposal.find(params[:id])
    @proposal.rejected!

    flash[:notice] = 'Proposta recusada com sucesso.'
    redirect_to my_proposals_path
  end


  private

  def find_ad
    @ad = Ad.find(params[:ad_id])
  end

  def proposal_params
    params.require(:proposal).permit(:description, :requested_knowledge,
                                     :email, :day_period, :meeting_type)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @profile = Profile.find params[:profile_id]
    @profile_review = @profile.profile_reviews.new
  end

  def create
    @profile = Profile.find params[:profile_id]
    @profile_review = @profile.profile_reviews.new(profile_review_params)
    @profile_review.user = current_user
    @profile_review.save
    redirect_to @profile
  end

  private

  def profile_review_params
    params.require(:profile_review).permit(:rating, :comment)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_profile
    current_user.profile if current_user && current_user.profile && current_user.profile.persisted?
  end
end

app/views/ads/_ad.html.erb
<div class="box-ad">
  <h3><%= link_to ad.title, ad_path(ad) %></h3>
  <dl class="dl-horizontal">
      <dt>O que quero aprender:</dt><dd><%= ad.requested_knowledge  %></dd>
      <dt>O que posso ensinar:</dt><dd> <%= ad.offered_knowledge %></dd>
      <dt>Formato:</dt><dd><%= ad.meeting_type%><br></dd>
      <dt>Periodo:</dt><dd><%= ad.day_period%><br></dd>
      <dt>Localizacao:</dt><dd><%= ad.location%><br></dd>
      <dt>Quando:</dt><dd><%= ad.avaliability%><br></dd>
  </dl>
  <%= link_to "Criado por #{ad.user.name}", ad.user.profile %>
</div>

app/views/ads/_form.html.erb
<%= form_for  @ad do |f| %>
  <div class="form-group">
    <%= f.label :title, 'Titulo' %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :requested_knowledge %>
    <%= f.text_field :requested_knowledge, class: 'form-control' %>
  </div>

 <div class="form-group">
   <%= f.label :offered_knowledge %>
   <%= f.text_field :offered_knowledge, class: 'form-control' %>
 </div>

 <div class="form-group">
   <%= f.label :meeting_type %>
   <%= f.text_field :meeting_type, class: 'form-control' %>
 </div>

 <div class="form-group">
   <%= f.label :day_period %>
   <%= f.text_field :day_period, class: 'form-control' %>
 </div>

 <div class="form-group">
   <%= f.label :location %>
   <%= f.text_field :location, class: 'form-control' %>
 </div>

 <div class="form-group">
   <%= f.label :avaliability %>
   <%= f.text_field :avaliability, class: 'form-control' %>
 </div>

   <%= f.submit 'Enviar', class: "btn btn-default" %>
<% end %>

app/views/ads/edit.html.erb
<h1>Editar anúncio</h1>
<div class='row'>
  <div class='col-md-12'>
    <%= render 'form' %>
  </div>
</div>

app/views/ads/filter.html.erb
<div class='row'>
  <h1>Resultado da busca: "<%=@busca%>"</h1>
</div>

<div class='row'>
<% if @ads.empty? %>
  <div class="alert alert-warning">
    <h3>Não encontramos resultados para a busca!</h3>
  </div>
<% end %>
</div>

<div class='row'>
  <% @ads.each do |ad|%>
  <div class='col-xs-12 col-sm-4 col-md-4 .col-lg-3'>
    <h3><%= render ad %></div>
  <% end %>
</div>

app/views/ads/index.html.erb
<div class='row'>
  <% @ads.each do |ad|%>
  <div class='col-xs-12 col-sm-4 col-md-4 .col-lg-3'>
    <%= render ad %>
   </div>
  <% end %>
</div>

app/views/ads/new.html.erb
<h1>Novo anúncio</h1>
  <div class='row'>
    <div class='col-md-12'>
     <%= form_for  @ad do |f| %>
        <div class="form-group">
          <%= f.label :title, 'Titulo' %>
          <%= f.text_field :title, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :requested_knowledge %>
          <%= f.text_field :requested_knowledge, class: 'form-control' %>
        </div>

       <div class="form-group">
         <%= f.label :offered_knowledge %>
         <%= f.text_field :offered_knowledge, class: 'form-control' %>
       </div>

       <div class="form-group">
         <%= f.label :meeting_type %>
         <%= f.text_field :meeting_type, class: 'form-control' %>
       </div>

       <div class="form-group">
         <%= f.label :day_period %>
         <%= f.text_field :day_period, class: 'form-control' %>
       </div>

       <div class="form-group">
         <%= f.label :location %>
         <%= f.text_field :location, class: 'form-control' %>
       </div>

       <div class="form-group">
         <%= f.label :avaliability %>
         <%= f.text_field :avaliability, class: 'form-control' %>
       </div>

         <%= f.submit 'Enviar', class: "btn btn-default" %>
     <% end %>
    </div>
  </div>

app/views/ads/show.html.erb
<div class='row'>
  <h1><%= @ad.title %></h1>

  <dl class="dl-horizontal">
    <dt>Status</dt><dd><%= I18n.t @ad.status %></dd>
    <dt>O que quero aprender:</dt><dd><%= @ad.requested_knowledge  %></dd>
    <dt>O que posso ensinar:</dt><dd> <%= @ad.offered_knowledge %></dd>
    <dt>Formato:</dt><dd><%= @ad.meeting_type%><br></dd>
    <dt>Periodo:</dt><dd><%= @ad.day_period%><br></dd>
    <dt>Localizacao:</dt><dd><%= @ad.location%><br></dd>
    <dt>Quando:</dt><dd><%= @ad.avaliability%><br></dd>
  </dl>
</div>

<% if @ad.user != current_user and @current_user_proposal.nil? and @ad.active? %>
  <%= link_to 'Enviar proposta', new_ad_proposal_path(@ad), class: 'btn btn-success navbar-btn'%>
<% elsif !@current_user_proposal.nil? %>
  <h1>Dados da sua proposta:</h1>
  <dl class="dl-horizontal">
    <dt>Proposta:</dt><dd><%= @current_user_proposal.description %></dd>
    <dt>O que quero aprender: </dt><dd> <%= @current_user_proposal.requested_knowledge %></dd>
    <dt>Email:</dt><dd> <%= @current_user_proposal.email %></dd>
    <dt>Periodo do dia:</dt><dd> <%= @current_user_proposal.day_period %></dd>
    <dt>Formato:</dt><dd> <%= @current_user_proposal.meeting_type %></dd>
    </dt>
<% end %>


<% if @ad.user == current_user and @ad.active? %>
  <%= link_to 'Editar anúncio', edit_ad_path(@ad), class: 'btn btn-primary navbar-btn' %>
  <%= link_to 'Encerrar anúncio', ad_finish_path(@ad), method: :post, class: 'btn btn-danger navbar-btn' %>
  <%= link_to 'Cancelar anúncio', ad_cancel_path(@ad), method: :post, class: 'btn btn-danger navbar-btn' %>
<% end %>

app/views/home/index.html.erb
<h2 class='text-center welcome'>Bem vindo ao melhor compartilhamento de conhecimento.</h2>

<div class='row'>
  <% if current_user and !current_user.profile %>
    <h4>Você ainda nao completou o seu perfil, <%= link_to 'Clique aqui', new_profile_path %> para continuar</h4>
  <% end %>
</div>

<div class='row'>
    <%if user_signed_in? %>
      <% if current_user.ads.where(status: :active).empty? %>
        <%= link_to 'Criar Anuncio', new_ad_path, class:'btn btn-success' %>
      <% end %>
    <% end %>
</div>

<div class='row'>
<% if @ads.empty? %>
  <div class="alert alert-info">
    <h4>Não temos anúncios por agora em breve novos anúncios para você. Volte logo!</h4>
  </div>
<% end %>
</div>

<div class='row'>
  <% @ads.each do |ad|%>
  <div class='col-xs-12 col-sm-4 col-md-4 col-lg-4'>
    <%= render ad %>
  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Troca Conhecimento</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>

    <div class='row text-center'>
      <%= image_tag 'troca_conhecimento.png', class: 'logo_img' %>
      <h1 class='title-welcome'>Troca de Conhecimento</h1>
      <h4 class='subtitle-welcome'>Aprender é viver</h4>
    </div>

    <nav class="navbar navbar-default">
      <div class="container">
        <%= render 'shared/navbar' %>
      </div>
    </nav>

    <main>
      <div class='container main'>
        <%= render 'shared/alerts'%>
        <%= yield %>
      </div>
    </main>
    <div class="footer-bottom">
      <div class="container">
        <div class="row">
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <div class="copyright"> © 2017 - CampusCode </div>
          </div> <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <div class="design"> Imersão Web - Turma de Férias Julho. </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/profiles/_form.html.erb
<div class='row'>
  <div class='col-md-12'>
  <%= form_for @profile do |f| %>
    <div class="form-group">
      <%= f.label :name%>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :birth_date %>
      <%= f.date_field :birth_date, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :city %>
      <%= f.text_field :city, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :state %>
      <%= f.text_field :state, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :skills %>
      <%= f.text_area :skills, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :photo %>
      <%= f.file_field :photo %>
    </div>
    <%= f.submit 'Enviar', class: "btn btn-default" %>
  <% end %>
  </div>
</div>

app/views/profiles/edit.html.erb
<div class='row'>
<%= render 'form' %>
</div>

app/views/profiles/my_send_proposals.html.erb
<% if @profile_proposals.empty?%>
  <h1> Voce nao tem propostas cadastradas </h1>
<% else %>
  <% if current_user.proposals.any? %>
    <h1> Suas propostas: </h1>
  <% @profile_proposals.each do |proposal|%>
    <dl class="dl-horizontal">
      <dt>Minhas qualificaçoes sobre o tema:</dt><dd> <%= proposal.description %></dd>
      <dt>Conhecimento que desejo aprender:</dt><dd> <%= proposal.requested_knowledge %></dd>
      <dt>Email:</dt><dd> <%= proposal.email %></dd>
      <dt>Periodo do dia:</dt><dd> <%= proposal.day_period %></dd>
      <dt>Formato:</dt><dd> <%= proposal.meeting_type %></dd>
      <dt>Status:</dt><dd> <%= proposal.status %></dd>
    </dl>
    <% if proposal.approved? %>
      <% if proposal.ad.user.profile.has_review_from_user? current_user %>
        <p>Profile já avaliado</p>
      <% else %>
        <%= link_to 'Avaliar troca de conhecimento', new_profile_review_path(proposal.ad.user.profile), class: 'btn btn-default'%>
      <% end %>
    <% end %>
  <% end %>
 <% end %>
<% end %>

<%= link_to 'Voltar', root_path, class: 'btn btn-default'%>

app/views/profiles/new.html.erb
<div class='row'>
<%= render 'form' %>
</div>

app/views/profiles/show.html.erb
<div class='row'>
  <% if @profile.photo.file? %>
    <%= image_tag @profile.photo.url(:medium) %>
  <% else %>
    <%= image_tag 'blank_profile_photo.jpg' %>
  <% end %>
  <h3><%= @profile.name %></h3>
  <dl class="dl-horizontal">
    <dt>Data de Nascimento:</dt><dd><%= I18n.l(@profile.birth_date) %></dd>
    <dt>Cidade:</dt><dd><%= @profile.city %></dd>
    <dt>Estado:</dt><dd><%= @profile.state %></dd>
  </dl>
  <label>Conhecimentos:</label>
  <p><%= @profile.skills %></p>
  <% if @profile.user == current_user  %>
    <%= link_to 'Editar meu perfil', edit_profile_path, class: 'btn btn-default' %>
  <% end %>
  <%= link_to 'Ver Anúncios', profile_ads_path(@profile), class: 'btn btn-default' %>

  <h4>Avaliações</h4>
  <% @profile.profile_reviews.each do |review| %>
    <dl class="dl-horizontal">
      <dt>Nota:</dt><dd><%= review.rating %></dd>
      <dt>Comentários:</dt><dd><p><%= review.comment %></p></dd>
    </dl>
  <% end %>
</div>

app/views/proposals/_proposal.html.erb
<h2>Proposta #<%= proposal.id %></h2>
<p>
  <%= proposal.description %>
</p>
<h4>Mais detalhes:</h4>
<dl>
  <dt>Anuncio:</dt><dd><%=link_to proposal.ad.requested_knowledge, proposal.ad %></dd>
  <dt>Conhecimento que desejo aprender:</dt><dd> <%= proposal.requested_knowledge %></dd>
  <dt>Email:</dt><dd> <%= proposal.email %></dd>
  <dt>Periodo do dia:</dt><dd> <%= proposal.day_period %></dd>
  <dt>Formato:</dt><dd> <%= proposal.meeting_type %></dd>
</dl>
<h4>Ações</h4>
<%= link_to 'Aceitar', approve_proposal_path(proposal), method: :post, class: 'btn btn-default'  %>
<%= link_to 'Recusar', reject_proposal_path(proposal), method: :post, class: 'btn btn-default'  %>

app/views/proposals/my_proposals.html.erb
<h2> Minhas propostas</h2>

<div id="proposal-approved" >
  <h3> Aprovadas </h3>
  <% @proposals_approved.each do |proposal| %>
  <div id="proposal-<%= proposal.id %>" >
    <%= render proposal%>
  </div>
  <%end%>
</div>

<div id="proposal-pending" >
  <h3> Pendentes </h3>
  <% @proposals_pending.each do |proposal| %>
  <div id="proposal-<%= proposal.id %>" >
    <%= render proposal%>
  </div>
  <%end%>
</div>

<div id="proposal-rejected" >
  <h3> Rejeitadas </h3>
  <% @proposals_rejected.each do |proposal| %>
  <div id="proposal-<%= proposal.id %>" >
    <%= render proposal%>
  </div>
  <%end%>
</div>

<%= link_to 'Voltar', root_path, class: 'btn btn-default' %>

app/views/proposals/new.html.erb
<% if @proposal.errors.full_messages.any? %>
    <div class="alert alert-danger">
        <% @proposal.errors.full_messages.each do |message| %>
            <label><%= message %></label>
        <% end %>
    </div>
<% end %>
<div class='row'>
  <h1>Enviar Proposta</h1>
  <div class='col-md-6'>
  <%= form_for [@ad, @proposal] do |f| %>

    <div class="form-group">
            <%= f.label :description, 'Minhas qualificaçoes sobre o tema' %>
            <%= f.text_field :description, class: 'form-control'%>
        </div>

        <div class="form-group">
            <%= f.label :requested_knowledge, 'Conhecimento que desejo aprender' %>
            <%= f.text_field :requested_knowledge, class: 'form-control' %>
        </div>

        <div class="form-group">
            <%= f.label :email, 'Email' %>
            <%= f.email_field :email, class: 'form-control'%>
        </div>

        <div class="form-group">
            <%= f.label :day_period, 'Periodo do dia' %>
            <%= f.text_field :day_period, class: 'form-control' %>
        </div>

        <div class="form-group">
            <%= f.label :meeting_type, 'Formato' %>
            <%= f.text_field :meeting_type, class: 'form-control' %>
        </div>
        <%= f.submit 'Enviar', class: "btn btn-default" %>
    <% end %>
   </div>
</div>

app/views/reviews/new.html.erb
<%= form_for @profile_review do |f| %>
  <div class="form-group">
    <%= f.label :rating %>
    <%= f.select(:rating) do %>
      <% (0..5).each do |number| %>
        <%= content_tag(:option, number, value: number) %>
      <% end %>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :comment %>
    <%= f.text_area :comment, class: 'form-control' %>
  </div>

  <%= f.submit 'Enviar', class: 'btn btn-default' %>
<% end %>

app/views/shared/_alerts.html.erb
<% if flash[:success]%>
<div class="row">
  <div class='alert alert-success'>
    <%= flash[:success]%>
  </div>
</div>
<% end %>

<% if flash[:error]%>
  <div class="row">
    <div class='alert alert-danger'>
      <%= flash[:error]%>
    </div>
  </div>
  <% end %>

<% if flash[:notice]%>
  <div class="row">
    <div class='alert alert-info'>
      <%= flash[:notice]%>
    </div>
  </div>
 <% end %>

<% if flash[:alert]%>
<div class="row">
  <div class='alert alert-warning'>
  <%= flash[:alert]%>
  </div>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-header">
  <a class="navbar-brand" href="/">Troca Conhecimento</a>
</div>

<div class="collapse navbar-collapse">
  <%= form_tag(filter_ads_path, {method: "get", class: "navbar-form navbar-left" }) do %>
    <%= label_tag(:filter, "Busca") %>
    <%= text_field_tag(:filter, nil,class: 'form-control') %>
    <%= submit_tag("Buscar" ,{class: "btn btn-success"}) %>
  <% end %>

  <div class="nav navbar-nav navbar-right">
  <% if user_signed_in? %>
    <% if current_profile %>
      <% if current_profile.photo.file? %>
        <%= image_tag current_profile.photo.url(:thumb), class:'img-circle', size:'25x25' %>
      <%else%>
        <%= image_tag 'blank_profile_photo.jpg', class:'img-circle', size:'25x25' %>
      <%end%>
      <%= link_to current_profile.name, profile_path(current_profile), class: 'navbar-link' %>
      <%= link_to 'Minhas propostas', my_send_proposals_path, class: 'btn btn-success navbar-btn' %>
      <%= link_to 'Propostas recebidas', my_proposals_path, class: 'btn btn-success navbar-btn' %>
    <% end %>
    <%= link_to 'Logout', destroy_user_session_path, method: 'delete', class: 'btn btn-danger navbar-btn' %>
  <% else %>
    <%= link_to 'Cadastrar', new_user_registration_path, class: 'btn btn-success navbar-btn' %>
    <%= link_to "Log in", new_user_session_path, class: 'btn btn-success navbar-btn'%>
  <% end %>
  </div>

</div>